name: Deploy Web ke VPS Nginx

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout kode dari repo
      uses: actions/checkout@v4

    - name: Deploy ke VPS melalui SSH
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        # BARIS BARU INI DITAMBAHKAN
        port: 2345 
        
        script: |
          # Perintah yang akan dijalankan di dalam VPS
          cd /var/www/bulenetwork.com/html
          git pull origin main
